added controller for CRUD operations
wolox-training/jg-java pull request #2
Opened 2019-07-29 21:23 UTC by jcgrethe

## Summary
- CRUD operation for book model created.
## Screenshots
![Screenshot from 2019-07-29 18-22-36](https://user-images.githubusercontent.com/26804047/62083697-f4180c80-b22d-11e9-89a0-cfedf0915db6.png)
![Screenshot from 2019-07-29 18-23-13](https://user-images.githubusercontent.com/26804047/62083698-f4180c80-b22d-11e9-96a7-a67bb2025433.png)

2019-07-29 22:08 UTC, Jimenarosello requested changes
Nice job! Just a few tips 😃

2019-07-29 22:08 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +    public Book updateBook(@RequestBody Book book, @PathVariable Long id)
You could use `update` instead of `updateBook` to follow the same line you used with the other methods

2019-07-29 22:08 UTC, Jimenarosello commented on src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +@ResponseStatus(code = HttpStatus.NOT_FOUND, reason = "Actor Not Found")
I think the status code and reason don't match the Exception, you could use a status code `400 (BAD_REQUEST)` and the reason could be something like `"The book you attempted to modify did not have the expected id"`.

2019-07-29 22:08 UTC, Jimenarosello commented on src/main/java/wolox/training/exceptions/BookNotFoundException.java
> +@ResponseStatus(code = HttpStatus.NOT_FOUND, reason = "Actor Not Found")
The reason should be `"Book not found"`

2019-07-29 22:08 UTC, Jimenarosello commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    Book findByTitle(String title);
Return an `Optional<Book>` instead of a `Book`. Same in line 12

2019-07-29 22:08 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +
I think the default constructor (empty, with no parameters), which is required by JPA, is missing

2019-07-29 22:08 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +        return bookRepository.findByTitle(bookTitle);
You could add `.orElseThrow(BookNotFoundException::new)` at the end of the line

2019-07-30 13:38 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/Book.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
I recommend using GenerationType.SEQUENCE for example:

@Id
**@GeneratedValue** (strategy = GenerationType.SEQUENCE, generator = “BOOK_SEQ”)
@SequenceGenerator (name = “BOOK_SEQ”, sequenceName = “BOOK_SEQ”)

With GenerationType.AUTO
Having two tables (book and user), I would use the same sequence for both.
If your first object is a book, it will be saved into the database with the id number 1.
If your second object is a user, this GenerationType will save it with the id number 2, since it shares the sequence counter.

With GenerationType.SEQUENCE
would generate a sequence for each table, independent of each other.

I leave a link where this topic is discussed.

- https://github.com/jhipster/generator-jhipster/issues/3109

Here they also recommend GenerationType.IDENTITY for these cases.
These solutions that I propose are designed for Postgres, when you have different database engines, you will have to see what strategy is appropriate in each case, because there are database engines that do not support all GenerationTypes.

2019-07-30 13:38 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/Book.java
> +    private String isbn;
In unique data like this, I would use "unique = true" in the column annotation

- @Column (nullable = false, unique = true)

2019-07-30 15:37 UTC, Gianni-Nicolas approved these changes

2019-07-30 15:40 UTC, Jimenarosello approved these changes
Nice job 😄

2019-07-30 15:41 UTC, merged