Swagger
wolox-training/jg-java pull request #4
Opened 2019-07-30 18:52 UTC by jcgrethe

## Summary
- Added swagger doc for Book model and controller
## Screenshots
![Screenshot from 2019-07-30 15-51-53](https://user-images.githubusercontent.com/26804047/62156761-03589200-b2e2-11e9-8c41-3f89c826fae1.png)

2019-07-30 19:26 UTC, Gianni-Nicolas approved these changes

2019-07-30 19:34 UTC, GNico95 commented on src/main/java/wolox/training/config/swaggerConfiguration.java
> +            .description("REST API for libraries")
I recommend changing the default swagger message in .description (). You could put a description of what your application does.

2019-07-30 19:38 UTC, Gianni-Nicolas submitted a review, later dismissed

2019-07-30 21:00 UTC, Jimenarosello requested changes
Looks good, just one small change :)

2019-07-30 21:00 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +            @ApiResponse(code = 404, message = "Bad id")
I think the code here should be 400 (BookMismatchException?)

2019-07-30 21:25 UTC, jcgrethe commented on src/main/java/wolox/training/controllers/BookController.java
> +            @ApiResponse(code = 404, message = "Bad id")
yes, my mistake

2019-07-31 18:46 UTC, Jimenarosello approved these changes

2019-08-01 17:42 UTC, Gianni-Nicolas approved these changes

2019-08-01 21:16 UTC, merged