added validation for models
wolox-training/jg-java pull request #5
Opened 2019-07-30 19:21 UTC by jcgrethe

## Summary
- Added preconditions validations for setter in Book and User models

2019-07-30 19:28 UTC, Gianni-Nicolas approved these changes

2019-07-30 20:10 UTC, Gianni-Nicolas requested changes

2019-07-30 20:10 UTC, GNico95 commented on src/main/java/wolox/training/models/Book.java
> +        Preconditions.checkNotNull(isbn);
You could check that the isbn is only have numerical characters.

2019-07-30 21:06 UTC, Jimenarosello requested changes
Nice job 👍 a few tips and it's ready to go

2019-07-30 21:06 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +        Preconditions.checkNotNull(genre);
The method `checkNotNull(T element)` returns an object of type `T`, I think you should be able to do something like this:

`this.genre = Preconditions.checkNotNull(genre);` which is a bit cleaner :) 

The same goes for all uses of the method (but unfortunately it doesn't apply to the method `checkArgument`)

2019-07-31 15:43 UTC, Gianni-Nicolas approved these changes

2019-07-31 17:13 UTC, Jimenarosello approved these changes
Nice job 😄

2019-08-01 21:17 UTC, merged