open api service
wolox-training/jg-java pull request #7
Opened 2019-07-31 19:09 UTC by jcgrethe

## Summary
- Find books by ISBN
- If it isn't created in our database, it will search in the open library database and create it. 
## Screenshots

![Screenshot from 2019-07-31 16-05-49](https://user-images.githubusercontent.com/26804047/62240492-7f6bdc00-b3ad-11e9-9205-11f407a17e33.png)

2019-08-01 15:14 UTC, Gianni-Nicolas submitted a review, later dismissed

2019-08-01 17:10 UTC, Jimenarosello requested changes
Nice job :) just a few changes

2019-08-01 17:10 UTC, Jimenarosello commented on src/main/java/wolox/training/services/OpenLibraryService.java
> +            book.setTitle(obj.getString("title"));
Maybe you could use static constants for these tags (subtitle, publishers, name, etc.) since you might use them multiple times.

2019-08-01 17:10 UTC, Jimenarosello commented on src/main/java/wolox/training/services/OpenLibraryService.java
> +        conn.setRequestMethod("GET");
You could use HttpMethod.GET

2019-08-05 13:40 UTC, Jimenarosello approved these changes

2019-08-05 20:27 UTC, Gianni-Nicolas approved these changes

2019-08-05 20:29 UTC, merged