spring security
wolox-training/jg-java pull request #8
Opened 2019-07-31 21:14 UTC by jcgrethe

# Summary

- Spring security Implemented. Only creation of book and users are allowed without login
## Screenshot

![Screenshot from 2019-07-31 18-05-48](https://user-images.githubusercontent.com/26804047/62248622-f2ca1980-b3be-11e9-81b0-8af57f2dd734.png)
![Screenshot from 2019-07-31 18-12-56](https://user-images.githubusercontent.com/26804047/62248623-f2ca1980-b3be-11e9-9ce1-b0f0c2850d57.png)

2019-08-02 16:08 UTC, Jimenarosello requested changes
Nice job 😄 a few comments :)

2019-08-02 16:08 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UserController.java
> +        u.setPassword(passwordEncoder.encode(user.getPassword()));
The encoder should be in the setter method, and the `.save()` method should be the line after setting the password :) you can return the value directly like this: 

`return userRepository.save(u)`

2019-08-02 16:08 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/UserController.java
The controller should include a separate method to update the password (other than the standard `update` method). It should receive the params `oldPassword` and `newPassword`, compare the current password and the old one and only update the password with the new value if they match. 

And the standard `update` method should update every field individually, except the password, keeping the current one.

2019-08-02 16:08 UTC, Jimenarosello commented on src/main/java/wolox/training/models/User.java
> +    public void setPassword(String password) {
Include the encryption here 🙂 You could also add a password validation with Preconditions: not null, minimum amount of characters, whatever you prefer :)

2019-08-02 16:08 UTC, Jimenarosello commented on src/main/java/wolox/training/config/SecurityConfiguration.java
> +    @Autowired
I think you shouldn't need this method, let me know if there is any specific reason you configured it :) Same for UserDetailService (which I think is only used here)

2019-08-05 14:31 UTC, Jimenarosello approved these changes

2019-08-05 20:42 UTC, Gianni-Nicolas approved these changes

2019-08-05 20:45 UTC, merged